airports:
  - icao: KLOM
  - icao: KPHL
  - icao: KPNE
  - icao: KTTN
  - icao: KILG
  - icao: KLNS
  - icao: KPTW
  - icao: KABE
  - icao: KRDG
  - icao: KEWR
  - icao: KACY
refreshinterval: "5m"
metarsource: https://www.aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&hoursBeforeNow=5&mostRecentForEachStation=true&stationString={ICAOLIST}